--- # delius-training all.yml
region: eu-west-2
project_name: delius
environment_name: delius-training
simple_environment_name: training
ndelius_version: "4.4.14"
catalog: DCAT
data_classification: unclassified-data
required_patches:
  p20807155:
      filename: p20807155_112040_Linux-x86-64.zip
      description: ORA-07445 Updating Table with CLOB
      grid_patch: false
      database_patch: true
