---

- hosts: localhost
  pre_tasks:

    - name: Checkout our roles repo
      git:
        repo: https://github.com/ministryofjustice/hmpps-ansible-roles.git
        dest: "{{ playbook_dir }}/roles"
        version: "{{ branch|default('master') }}"

    - name: Default to dev if environment is not set
      set_fact:
        target_environment: "{{ target_environment|default('dev') }}"

    - name: Search for our files that match our environment
      find:
        paths: "{{ playbook_dir }}"
        recurse: yes
        patterns: "*.credentials.yml, *.credentials.yaml"
      register: yaml_files

    - block:
        - name: Filter our results
          set_fact:
            yaml_results: "{{ yaml_files.files | rejectattr('path', 'search', 'prod') | rejectattr('path', 'search', 'common') | map(attribute='path')|list }}"
      when: target_environment == 'dev'

    - block:
        - name: Filter our results
          set_fact:
            yaml_results: "{{ yaml_files.files | selectattr('path', 'search', 'prod') | rejectattr('path', 'search', 'common') | map(attribute='path')|list }}"
      when: target_environment != 'dev'

    - name: Debug our list
      debug:
        msg: "{{ yaml_results | to_nice_json }}"

  tasks:
    - name: Run our create credentials role
      include: "{{ playbook_dir }}/local_tasks/run_generation.yml"
      with_items: "{{ yaml_results }}"
      loop_control:
        loop_var: vars_file

  environment:
    ANSIBLE_ROLES_PATH: "{{ playbook_dir }}/roles/roles"

  post_tasks:
    - name: Remove our roles repo
      file:
        path: "{{ playbook_dir }}/roles"
        state: absent

