--- # delius-core-sandpit all.yml
region: eu-west-2
project_name: delius-core
environment_name: delius-core-sandpit
simple_environment_name: sandpit
ndelius_version: "4.2.9"
catalog: DCAT
data_classification: unclassified-data
certificate_orchestration_override_renewal_period_in_days: 2
certificate_orchestration_override_replace_when_expiring_in_days: 1
certificate_orchestration_override_cert_expire_in_days: 3
certificate_orchestration_override_root_ca_cert_expire_in_days: 3