--- # delius_primarydb.yml

database_global_database: PRENDA
database_taf_service: PRENDA_TAF
database_primary_unique: PRENDA
database_primary_sid: PRENDA
rman_level_0_backup_duration_target: "21:00"
