--- # delius_primarydb.yml

database_global_database: PRDNDA
database_taf_service: PRDNDA_TAF
database_primary_unique: PRDNDA
database_primary_sid: PRDNDA
rman_level_0_backup_duration_target: "21:00"
rman_uncompressed_backup: Y
cfo_database_directory: "/u01/app/oracle/admin/{{ database_global_database }}/cfo/shared_files/National/cfo"
required_patches:
    p27659043:
      filename: p27659043_11204180417_Linux-x86-64.zip
      description: MES Bundle Patch for April 2017 PSU
      postinstall_sql: postinstall.sql
      grid_patch: false
      database_patch: true