--- # delius_standbydb1.yml

database_standby_unique: PRDNDAS1
database_standby_sid: PRDNDAS1
database_primary_unique: PRDNDA
required_patches:
    p27659043:
      filename: p27659043_11204180417_Linux-x86-64.zip
      description: MES Bundle Patch for April 2017 PSU
      postinstall_sql: postinstall.sql
      grid_patch: false
      database_patch: true